<?php
/**
 * Template Name: Lumen: Hero ancho completo
 * Template Post Type: page
 *
 * Keeps Lumen's header and footer, renders the leading Gutenberg block or
 * Elementor section as a true full-width hero, and applies the selected
 * sidebar only to the content that follows.
 *
 * @package CreceWebLumen
 */

$creceweb_sidebar_layout = \CreceWeb\Lumen\get_effective_sidebar_layout( 'page' );

/*
 * This template lets the hero define the page height. Standard templates keep
 * a viewport-filling shell for short editorial pages; retaining it here would
 * leave a large empty area after a hero-only page before the footer.
 *
 * Resolve the Gutenberg-only case before get_header() so the body receives a
 * stable class on the first paint. This avoids relying solely on :has(), which
 * previously allowed the generic shell height to win in some installations.
 * Elementor retains the progressive :has() fallback generated by the theme.
 */
$creceweb_template_page_id = (int) get_queried_object_id();
$creceweb_template_hero_only = false;
$creceweb_template_library_hero_only = false;
$creceweb_template_lumen_hero_only = false;

/**
 * Lumen Library patterns from Lite or Pro are full-width Gutenberg groups, not native
 * Cover blocks. They must stay in normal document flow; otherwise the Theme's
 * legacy hero-only flex filler can let the footer start before the pattern's
 * visual content has finished.
 *
 * @param array<string,mixed>|null $block Parsed leading block.
 * @return bool
 */
$creceweb_is_library_pattern_block = static function ( $block ): bool {
	if ( ! is_array( $block ) ) {
		return false;
	}

	$attrs      = is_array( $block['attrs'] ?? null ) ? $block['attrs'] : array();
	$class_name = (string) ( $attrs['className'] ?? '' );
	$inner_html = (string) ( $block['innerHTML'] ?? '' );

	return false !== strpos( $class_name, 'cw-lumen-pro-pattern--' )
		|| false !== strpos( $class_name, 'cw-lumen-lite-pattern--' )
		|| false !== strpos( $inner_html, 'cw-lumen-pro-pattern--' )
		|| false !== strpos( $inner_html, 'cw-lumen-lite-pattern--' );
};

if ( $creceweb_template_page_id > 0 && ! comments_open( $creceweb_template_page_id ) && 0 === (int) get_comments_number( $creceweb_template_page_id ) ) {
	$creceweb_template_content = (string) get_post_field( 'post_content', $creceweb_template_page_id );
	$creceweb_template_blocks  = has_blocks( $creceweb_template_content ) ? parse_blocks( $creceweb_template_content ) : array();
	$creceweb_template_hero    = \CreceWeb\Lumen\get_leading_full_width_block( $creceweb_template_blocks );

	if ( $creceweb_template_hero ) {
		$creceweb_template_remaining = \CreceWeb\Lumen\get_visible_blocks( array_slice( $creceweb_template_blocks, $creceweb_template_hero['index'] + 1 ) );
		$creceweb_template_hero_only = empty( $creceweb_template_remaining );
		$creceweb_template_library_hero_only = $creceweb_template_hero_only && $creceweb_is_library_pattern_block( $creceweb_template_hero['block'] ?? null );
		$creceweb_template_lumen_hero_only = $creceweb_template_hero_only && \CreceWeb\Lumen\block_has_lumen_hero_class( $creceweb_template_hero['block'] ?? null );

		if ( $creceweb_template_library_hero_only ) {
			$creceweb_template_hero_only = false;
		}
	}
}

add_filter(
	'body_class',
	static function ( $classes ) use ( $creceweb_template_hero_only, $creceweb_template_library_hero_only, $creceweb_template_lumen_hero_only ) {
		$classes[] = 'cw-template--hero-full-width';

		if ( $creceweb_template_hero_only ) {
			$classes[] = 'cw-template--hero-only';
		}

		if ( $creceweb_template_library_hero_only ) {
			$classes[] = 'cw-template--library-hero-only';
		}

		if ( $creceweb_template_lumen_hero_only ) {
			$classes[] = 'cw-template--lumen-hero-only';
		}

		return array_values( array_unique( $classes ) );
	}
);

$GLOBALS['creceweb_lumen_hero_only_page'] = $creceweb_template_hero_only;
$GLOBALS['creceweb_lumen_library_hero_only_page'] = $creceweb_template_library_hero_only;
$GLOBALS['creceweb_lumen_hero_base_only_page'] = $creceweb_template_lumen_hero_only;

get_header();
?>
<main id="cw-main-content" class="cw-template-main cw-template-main--hero<?php echo $creceweb_template_hero_only ? ' cw-template-main--hero-only' : ''; ?>"<?php echo $creceweb_template_hero_only ? ' style="display:flex;flex:1 1 0;flex-direction:column;min-height:0"' : ''; ?>>
	<?php while ( have_posts() ) : the_post(); ?>
		<?php
		$creceweb_raw_content = (string) get_the_content();
		$creceweb_blocks      = has_blocks( $creceweb_raw_content ) ? parse_blocks( $creceweb_raw_content ) : array();
		$creceweb_hero_block  = \CreceWeb\Lumen\get_leading_full_width_block( $creceweb_blocks );
		$creceweb_hero_html   = '';
		$creceweb_content_html = '';
		$creceweb_has_after_content = false;
		$creceweb_is_elementor       = false;

		if ( $creceweb_hero_block ) {
			$creceweb_hero_html = \CreceWeb\Lumen\render_blocks( array( $creceweb_hero_block['block'] ) );
			$creceweb_remaining_blocks = \CreceWeb\Lumen\get_visible_blocks( array_slice( $creceweb_blocks, $creceweb_hero_block['index'] + 1 ) );
			$creceweb_content_html      = \CreceWeb\Lumen\render_blocks( $creceweb_remaining_blocks );
			$creceweb_has_after_content = ! empty( $creceweb_remaining_blocks );
		} else {
			ob_start();
			the_content();
			$creceweb_rendered_content = (string) ob_get_clean();
			$creceweb_elementor = \CreceWeb\Lumen\prepare_elementor_hero_content( $creceweb_rendered_content );
			$creceweb_hero_html         = (string) $creceweb_elementor['hero_html'];
			$creceweb_content_html      = (string) $creceweb_elementor['content_html'];
			$creceweb_has_after_content = (bool) $creceweb_elementor['has_content_after_hero'];
			$creceweb_is_elementor       = (bool) $creceweb_elementor['has_elementor_hero'];
		}

		$creceweb_has_hero     = '' !== trim( $creceweb_hero_html );
		$creceweb_has_comments = comments_open() || get_comments_number();
		$creceweb_is_hero_only  = $creceweb_has_hero && ! $creceweb_has_after_content && ! $creceweb_has_comments;
		$creceweb_is_library_hero_only = $creceweb_is_hero_only && ( false !== strpos( $creceweb_hero_html, 'cw-lumen-pro-pattern--' ) || false !== strpos( $creceweb_hero_html, 'cw-lumen-lite-pattern--' ) );
		$creceweb_is_lumen_hero_only = $creceweb_is_hero_only && ( false !== strpos( $creceweb_hero_html, 'cw-lumen-hero' ) || false !== strpos( $creceweb_hero_html, 'cw-lumen-pro-hero' ) );

		if ( $creceweb_is_library_hero_only ) {
			$creceweb_is_hero_only = false;
		}


			/* Gutenberg writes the Cover height inline (for example, 490px). On a
			 * genuine hero-only page, append a render-time override so the Cover can
			 * grow into the viewport space that remains after the real footer. */
			if ( $creceweb_is_hero_only && false !== strpos( $creceweb_hero_html, 'wp-block-cover' ) ) {
				$creceweb_hero_html = preg_replace_callback(
					'/<div\b(?=[^>]*\bwp-block-cover\b)([^>]*)>/i',
					static function ( $matches ) {
						$attributes = (string) $matches[1];
						$geometry   = 'flex:1 1 0;min-height:100%!important;height:100%!important;aspect-ratio:auto!important';

						if ( preg_match( '/\sstyle=(["\'])(.*?)\1/i', $attributes, $style_match ) ) {
							$style_value = rtrim( (string) $style_match[2], "; \t\n\r\0\x0B" );
							$replacement = ' style=' . $style_match[1] . $style_value . ';' . $geometry . $style_match[1];
							$attributes  = preg_replace( '/\sstyle=(["\'])(.*?)\1/i', $replacement, $attributes, 1 );
						} else {
							$attributes .= ' style="' . $geometry . '"';
						}

						return '<div' . $attributes . '>';
					},
					$creceweb_hero_html,
					1
				);
			}

		/*
		 * The footer is rendered after this template. Keep a narrow runtime flag so
		 * a real hero with no later editorial content can meet the footer directly.
		 * Pages with comments are not hero-only: the comments are their posterior
		 * content and retain the normal rhythm before the footer.
		 */
		$GLOBALS['creceweb_lumen_hero_only_page'] = $creceweb_is_hero_only;
		$GLOBALS['creceweb_lumen_library_hero_only_page'] = $creceweb_is_library_hero_only;
		$GLOBALS['creceweb_lumen_hero_base_only_page'] = $creceweb_is_lumen_hero_only;
		?>
		<?php
		$creceweb_post_hero_full_canvas = 'none' === $creceweb_sidebar_layout && $creceweb_has_after_content;
		$creceweb_entry_classes = 'cw-entry cw-entry--hero'
			. ( $creceweb_is_hero_only ? ' cw-entry--hero-only' : '' )
			. ( $creceweb_post_hero_full_canvas ? ' cw-entry--full-canvas' : '' );
		?>
		<article id="post-<?php the_ID(); ?>" <?php post_class( $creceweb_entry_classes ); ?><?php echo $creceweb_is_hero_only ? ' style="display:flex;flex:1 1 0;flex-direction:column;min-height:0"' : ''; ?>>
			<?php if ( '' !== trim( $creceweb_hero_html ) ) : ?>
				<section class="cw-hero-template__hero<?php echo $creceweb_is_elementor ? ' cw-hero-template__hero--elementor' : ''; ?>" data-cw-lumen-hero="1"<?php echo $creceweb_is_hero_only ? ' style="display:flex;flex:1 1 0;flex-direction:column;min-height:0"' : ''; ?>>
					<?php echo $creceweb_hero_html; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Rendered WordPress/Elementor markup. ?>
				</section>
			<?php endif; ?>

			<?php // The sidebar belongs only to real content after the hero; never render it by itself. ?>
			<?php if ( $creceweb_has_after_content ) : ?>
				<?php if ( 'none' === $creceweb_sidebar_layout ) : ?>
					<?php /*
					 * No-sidebar pages share the same post-Hero canvas contract as
					 * Lumen: Ancho completo. Avoid the sidebar-layout wrappers here:
					 * they intentionally constrain editorial/sidebar compositions and
					 * also trigger compatibility CSS in extensions. Keeping the content
					 * as a direct .entry-content child of .cw-entry--full-canvas lets the
					 * Theme's existing full-canvas rules remain the single owner of width.
					 */ ?>
					<div class="cw-hero-template__content--full-canvas entry-content wp-block-post-content" data-cw-lumen-hero-content="1">
						<?php echo $creceweb_content_html; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Rendered WordPress/Elementor markup. ?>
						<?php wp_link_pages(); ?>
					</div>
				<?php else : ?>
					<div class="cw-hero-template__layout cw-screen-layout cw-screen-layout--<?php echo esc_attr( $creceweb_sidebar_layout ); ?>">
						<div class="cw-hero-template__content cw-screen-layout__content entry-content wp-block-post-content" data-cw-lumen-hero-content="1">
							<?php echo $creceweb_content_html; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Rendered WordPress/Elementor markup. ?>
							<?php wp_link_pages(); ?>
						</div>
						<?php get_sidebar(); ?>
					</div>
				<?php endif; ?>
			<?php endif; ?>
			<?php if ( comments_open() || get_comments_number() ) { comments_template(); } ?>
		</article>
	<?php endwhile; ?>
</main>
<?php get_footer();
